version: "3.9"
services:
    web:
        build: .
        ports:
            - "5001:443"
            - "5000:80"
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - Telemetry__Endpoint=http://localhost:9411/api/v2/spans
            - ConnectionStrings__DefaultConnection=Server=sql_backend,1433;Database=ScoreboardAppDb;User Id=sa;Password=Pa@@word123;TrustServerCertificate=true
            - ConnectionStrings__CustomIdentityDatabase=Server=sql_identity,1433;Database=CustomIdentityDb;User Id=sa;Password=Pa@@word123;TrustServerCertificate=true
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Test1234!
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
            - ASPNETCORE_Environment=Development
            - TokenSettings__Secret=TotallySecretStringThatProbablyShouldntBeInThisFile
            - TokenSettings__Issuer=http://localhost:5000/
            - TokenSettings__Audience=""
            - TokenSettings__Expiry=5
            - TokenSettings__RefreshExpiry=1440
        depends_on:
            sql_backend:
                condition: service_started
            sql_identity:
                condition: service_started
        healthcheck:
          test: curl --silent --fail http://localhost:80/health || exit 1
          interval: 5s
          timeout: 10s
          retries: 3

    sql_backend:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        container_name: sql_backend
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Pa@@word123"
            ACCEPT_EULA: "Y"

    sql_identity:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
            - "1444:1433"
        environment:
            SA_PASSWORD: "Pa@@word123"
            ACCEPT_EULA: "Y"

    zipkin:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"